services:
  # Postgres DB
  rdb:
    image: postgres:14-alpine
    container_name: rdb
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pswd
      - POSTGRES_DB=trader
    healthcheck:
      test: bash -c "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      timeout: 10s
      retries: 10
