[tool.black]
line-length = 120
target-version = ['py310']
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 120
ignore = [
    "E203",
    "W503",
    "F403",
]
count = true

[tool.mypy]
warn_unused_configs = true
check_untyped_defs = true
explicit_package_bases = true
# disallow_untyped_defs = true
ignore_missing_imports = true
exclude = '''
/(
    \.git
  | \.venv
)/
'''
