"""Add happened_to to event schema

Revision ID: 084507c778d8
Revises: 56890c529c6d
Create Date: 2024-08-13 11:31:22.519432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084507c778d8'
down_revision: Union[str, None] = '56890c529c6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('happen_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'happen_at')
    # ### end Alembic commands ###
