"""Add language column

Revision ID: 08ffc532f5b2
Revises: 261a2d0a27f7
Create Date: 2024-08-23 18:29:29.144593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08ffc532f5b2'
down_revision: Union[str, None] = '261a2d0a27f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'language')
    # ### end Alembic commands ###
