"""Add owner_id to game

Revision ID: 261a2d0a27f7
Revises: 506277df4df3
Create Date: 2024-08-22 18:04:50.552082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '261a2d0a27f7'
down_revision: Union[str, None] = '506277df4df3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key('game_owner_id_fkey', 'games', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('game_owner_id_fkey', 'games', type_='foreignkey')
    op.drop_column('games', 'owner_id')
    # ### end Alembic commands ###
